# Generated by Django 5.2.5 on 2025-08-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leiturasensor',
            name='valor',
        ),
        migrations.AddField(
            model_name='leiturasensor',
            name='valor_percentual',
            field=models.FloatField(default=0, help_text='Valor em porcentagem ( 0 a 100 )'),
            preserve_default=False,
        ),
    ]
