# Generated by Django 5.2.5 on 2025-10-28 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_remove_leiturasensor_valor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposensor',
            old_name='descricao',
            new_name='funcao',
        ),
        migrations.AddField(
            model_name='tiposensor',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 28, 19, 34, 56, 912509, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
