# Generated by Django 5.2.5 on 2025-10-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0003_rename_descricao_tiposensor_funcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposensor',
            name='exibir',
            field=models.BooleanField(default=True),
        ),
    ]
